CREATE OR REPLACE TRIGGER TRG_LATE_RETURN 
BEFORE UPDATE OF DETAIL_RETURNDATE, DETAIL_DUEDATE ON DETAILRENTAL 
BEGIN
  IF DETAIL_RETURNDATE is null THEN
    DETAIL_DAILYFEE := null;
  END IF;
  NULL;
END;
--I'm not sure the entire syntax, plus I'm out of time